---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-keyspaces-controller.app.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-keyspaces-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-keyspaces-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-keyspaces-controller.chart.name-version" . }}
rules:
- apiGroups:
  - keyspaces.services.k8s.aws
  resources:
  - keyspaces
  - tables
  verbs:
  - get
  - list
  - watch
