// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package type_

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.FieldDefinitions) != len(b.ko.Spec.FieldDefinitions) {
		delta.Add("Spec.FieldDefinitions", a.ko.Spec.FieldDefinitions, b.ko.Spec.FieldDefinitions)
	} else if len(a.ko.Spec.FieldDefinitions) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.FieldDefinitions, b.ko.Spec.FieldDefinitions) {
			delta.Add("Spec.FieldDefinitions", a.ko.Spec.FieldDefinitions, b.ko.Spec.FieldDefinitions)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KeyspaceName, b.ko.Spec.KeyspaceName) {
		delta.Add("Spec.KeyspaceName", a.ko.Spec.KeyspaceName, b.ko.Spec.KeyspaceName)
	} else if a.ko.Spec.KeyspaceName != nil && b.ko.Spec.KeyspaceName != nil {
		if *a.ko.Spec.KeyspaceName != *b.ko.Spec.KeyspaceName {
			delta.Add("Spec.KeyspaceName", a.ko.Spec.KeyspaceName, b.ko.Spec.KeyspaceName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TypeName, b.ko.Spec.TypeName) {
		delta.Add("Spec.TypeName", a.ko.Spec.TypeName, b.ko.Spec.TypeName)
	} else if a.ko.Spec.TypeName != nil && b.ko.Spec.TypeName != nil {
		if *a.ko.Spec.TypeName != *b.ko.Spec.TypeName {
			delta.Add("Spec.TypeName", a.ko.Spec.TypeName, b.ko.Spec.TypeName)
		}
	}

	return delta
}
